services:
  journal-postgres:
    image: postgres:16
    container_name: journal_db
    ports:
      - "9000:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: journal_db
  journal-redis:
    container_name: journal-redis
    image: redis:7.2.4
    ports:
      - "9001:6379"